# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/federico/Shared/Projects/reti_logiche_project/RL.cache/wt [current_project]
set_property parent.project_path /media/federico/Shared/Projects/reti_logiche_project/RL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /media/federico/Shared/Projects/reti_logiche_project/RL.srcs/sources_1/new/10806848.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/federico/Shared/Projects/reti_logiche_project/RL.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files /media/federico/Shared/Projects/reti_logiche_project/RL.srcs/constrs_1/new/clock.xdc]


synth_design -top project_reti_logiche -part xc7a200tfbg484-1


write_checkpoint -force -noxdef project_reti_logiche.dcp

catch { report_utilization -file project_reti_logiche_utilization_synth.rpt -pb project_reti_logiche_utilization_synth.pb }
